import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Homes from "../../components/pages/Home";
import About from "../../components/pages/About";
import Resume from "../../components/pages/Resume";
import Services from "../../components/pages/services";
import Skills from "../../components/pages/Skills";
import Projects from "../../components/pages/Projects";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PORTFOLIO - Harshit Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Homes />
        <About />
        <Resume />
        <Services />
        <Skills />
        <Projects />
      </main>
    </>
  );
}
